package scan

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"sync"
)

// Some mods bundle well-known open-source libraries. A DLL that is
// byte-identical to one in the library's official NuGet package is that
// library, not a disguised payload. The list is generated by
// knownlibs/gen.go from nuget.org.

//go:embed knownlibs/knownlibs.json
var knownLibsJSON []byte

type knownLib struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	File    string `json:"file"`
}

var (
	knownLibsOnce sync.Once
	knownLibs     map[string]knownLib
)

// knownLibrary reports whether the file at p is a known library build.
func knownLibrary(p string) (knownLib, bool) {
	knownLibsOnce.Do(func() { json.Unmarshal(knownLibsJSON, &knownLibs) })
	f, err := os.Open(p)
	if err != nil {
		return knownLib{}, false
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, io.LimitReader(f, 64<<20)); err != nil {
		return knownLib{}, false
	}
	l, ok := knownLibs[hex.EncodeToString(h.Sum(nil))]
	return l, ok
}

// gameCopy reports whether the DLL at p is byte-identical to the file of
// the same name in the game's Managed folder (Unity and game assemblies that
// some mods ship by accident).
func gameCopy(p, managed string) bool {
	if managed == "" {
		return false
	}
	own := filepath.Join(managed, filepath.Base(p))
	a, err := os.Stat(p)
	if err != nil {
		return false
	}
	b, err := os.Stat(own)
	if err != nil || a.Size() != b.Size() {
		return false
	}
	ha, errA := fileSHA(p)
	hb, errB := fileSHA(own)
	return errA == nil && errB == nil && ha == hb
}

func fileSHA(p string) (string, error) {
	f, err := os.Open(p)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// Harmony and Cecil exist to rewrite other code (Harmony patches methods
// at runtime, Cecil edits assemblies on disk), so bundling one still needs a
// look; Newtonsoft.Json only reads and writes JSON.
func (l knownLib) severity() Severity {
	if l.Name == "Newtonsoft.Json" {
		return Medium
	}
	return High
}

func (l knownLib) describe() string {
	d := l.Name + " " + l.Version + ", identical to the official NuGet package"
	if l.severity() >= High {
		d += "; this library can rewrite game code, so check what the mod uses it for"
	}
	return d
}
